### PR TITLE
edit patient link now redirects to xforms edit patient form - XFRM-197

### PR DESCRIPTION
**Pull request by hanswurst**

### CODE REVIEW

**Comment by dkayiwa** [comment]
This is by design. As long as you have "usePatientXform" set to true, creating new and editing existing patients should use the patient xform instead of the default.

**Comment by dkayiwa** [comment]
@hanswurst did these formatting changes come after doing mvn clean install before committing?
Instead of creating a new method, just map the urls to the same existing method. You can take a look at http://stackoverflow.com/questions/3898442/spring-mvc-mapping-multiple-urls-to-same-controller

**Comment by hanswurst** [comment]
Thanks Daniel for the provided link. I changed it to what you suggested. 
As well as the code formatting that is now back to what it was before my commit. So the only thing different should now be the added request mapping

**Comment by dkayiwa** [comment]
@hanswurst can you squash these commits into one?

**Comment by hanswurst** [comment]
Can't we just leave them as they are?

**Comment by dkayiwa** [comment]
I cannot tell what changed and what did not, if you do not squash them into
one.

On Fri, Jun 12, 2015 at 1:22 PM, hanswurst <notifications@github.com> wrote:

> Can't we just leave them as they are?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openmrs/openmrs-module-xforms/pull/24#issuecomment-111440410>
> .
>



-- 
If we keep uppermost in our minds the unkind and unjust acts of others, we
shall find it impossible to love them as Christ has loved us; but if our
thoughts dwell upon the wondrous love and pity of Christ for us, the same
spirit will flow out to others.

**Comment by hanswurst** [comment]
Just click on the "files changed" tab...

**Comment by dkayiwa** [comment]
I also forgot to mention that our history is cleaner when we squash commits
in a pull request into one http://go.openmrs.org/pull-request-tips

On Fri, Jun 12, 2015 at 3:29 PM, hanswurst <notifications@github.com> wrote:

> Just click on the "files changed" tab...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openmrs/openmrs-module-xforms/pull/24#issuecomment-111476235>
> .
>



-- 
If we keep uppermost in our minds the unkind and unjust acts of others, we
shall find it impossible to love them as Christ has loved us; but if our
thoughts dwell upon the wondrous love and pity of Christ for us, the same
spirit will flow out to others.

**Comment by hanswurst** [comment]
Ok, I am actually working on the squash right now... :)

**Comment by hanswurst** [comment]
Think I got it....

**Pull request merged**
